baseURL = "https://tlfranko-star.github.io/technical-writing-portfolio/"
languageCode = 'en-us'
title = 'Documentation Portfolio for Tana Franko'
theme = "relearn"
relativeURLs = true

toml<br>[outputs]<br>home = ["HTML", "JSON"]<br>
