baseURL = "https://tlfranko-star.github.io/technical-writing-portfolio/"
languageCode = 'en-us'
title = 'Documentation Portfolio for Tana Franko'
theme = "PaperMod"
relativeURLs = true

# This section prevents the XML RSS feed from being served on the homepage,
# forcing the server to load the index.html file.
[outputs]
home = ["HTML", "JSON"]
